name: Update curriculum.tsv

on:
  schedule: # Runs at 00:00 UTC every day
    - cron: "0 0 * * *"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install selenium pandas tqdm
      - name: Run script
        run: python scraper.py
      - name: Commit and push if changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -A
          git commit -m "Auto-update curriculum.tsv" || exit 0 # Don't fail if nothing to commit
          git push
